### ISSUE TITLE
0.39-rc1: oMLX HEAD-f6f4269 + MiniCPM-V-4.6-4bit: AttributeError: 'VisionConfig' object has no attribute 'spatial_merge_size'

### ISSUE THREAD

**Issue by wp80878** [jundot/omlx#1314]
0.39-rc1 ： Can not work well with MiniCPM-V-4.6 

2026-05-20 05:38:27,622 - omlx.engine_pool - INFO - Loading model: MiniCPM-V-4.6-4bit
2026-05-20 05:38:27,628 - omlx.engine_core - INFO - MLX executor thread initialized: generation_stream = ThreadLocalStream(Device(gpu, 0), 3)
2026-05-20 05:39:09,098 - omlx.engine.vlm - INFO - Vision feature cache enabled (SSD: /Users/pengwei/.omlx/cache/vision_features)
2026-05-20 05:39:09,513 - omlx.patches.gated_delta_advance - INFO - GatedDeltaNet patch applied (body replacement): mlx_vlm.models.qwen3_5.language.Qwen3_5GatedDeltaNet
2026-05-20 05:39:09,513 - omlx.patches.qwen3_5_attention - INFO - Qwen3_5Attention patch applied (body replacement): mlx_vlm.models.qwen3_5.language.Qwen3_5Attention
2026-05-20 05:39:09,910 - omlx.scheduler - INFO - Loaded 1 additional EOS token(s) from generation_config.json: {248044}
2026-05-20 05:39:09,910 - omlx.scheduler - INFO - Enlarging paged cache block_size=256 to 2048 for ArraysCache hybrid model (reduces boundary snapshot overhead)
2026-05-20 05:39:09,910 - omlx.scheduler - INFO - paged SSD-only mode: max_blocks=100000, block_size=2048 tokens
2026-05-20 05:39:09,914 - omlx.cache.paged_cache - INFO - PagedCacheManager initialized: block_size=2048, initial_blocks=256, max_blocks=100000, max_tokens=204800000
2026-05-20 05:39:09,917 - omlx.cache.paged_ssd_cache - INFO - Scanning SSD cache directory: /Users/pengwei/.omlx/cache
2026-05-20 05:39:09,917 - omlx.cache.paged_ssd_cache - INFO - SSD cache scan complete: scanned=0, indexed=0, errors=0, total_size=0 B
2026-05-20 05:39:09,917 - omlx.cache.paged_ssd_cache - INFO - PagedSSDCacheManager initialized: dir=/Users/pengwei/.omlx/cache, max_size=185.81 GB, existing_files=0, disk_free=1438.77 GB, cache_used=0 B
2026-05-20 05:39:09,917 - omlx.cache.paged_cache - INFO - paged SSD cache manager connected to PagedCacheManager
2026-05-20 05:39:09,917 - omlx.cache.prefix_cache - INFO - PagedSSDCacheManager connected to BlockAwarePrefixCache
2026-05-20 05:39:09,917 - omlx.scheduler - INFO - paged SSD cache enabled: cache_dir=/Users/pengwei/.omlx/cache, max_size=185.81 GB, block_size=2048 tokens
2026-05-20 05:39:09,917 - omlx.scheduler - INFO - paged SSD cache enabled: /Users/pengwei/.omlx/cache, block_size=2048, max_blocks=100000
2026-05-20 05:39:09,918 - omlx.engine_core - INFO - Engine started
2026-05-20 05:39:09,963 - omlx.engine.vlm - INFO - VLM tool calling enabled: parser=qwen3_coder
2026-05-20 05:39:09,966 - omlx.engine.vlm - INFO - VLMBatchedEngine loaded: /Users/pengwei/.omlx/models/MiniCPM-V-4.6-4bit
2026-05-20 05:39:09,974 - omlx.engine_pool - INFO - Loaded model: MiniCPM-V-4.6-4bit (actual: 2.45GB, estimated: 2.11GB, total: 2.11GB)
2026-05-20 05:39:09,979 - omlx.engine.vlm - INFO - Structured output requires xgrammar. Reinstall with: brew reinstall omlx --with-grammar
2026-05-20 05:39:10,254 - omlx.engine_core - ERROR - Engine loop error: 'VisionConfig' object has no attribute 'spatial_merge_size'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/omlx/HEAD-f6f4269/libexec/lib/python3.11/site-packages/omlx/engine_core.py", line 205, in _engine_loop
    output = await loop.run_in_executor(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.15_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/omlx/HEAD-f6f4269/libexec/lib/python3.11/site-packages/omlx/scheduler.py", line 5444, in step
    scheduled, rejected = self._schedule_waiting()
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/omlx/HEAD-f6f4269/libexec/lib/python3.11/site-packages/omlx/scheduler.py", line 4691, in _schedule_waiting
    prefilled_cache, last_token = self._do_external_prefill(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/omlx/HEAD-f6f4269/libexec/lib/python3.11/site-packages/omlx/scheduler.py", line 1781, in _do_external_prefill
    self.model(input_arr[:, :n_to_process], cache=prompt_cache, **model_kwargs)
  File "/opt/homebrew/Cellar/omlx/HEAD-f6f4269/libexec/lib/python3.11/site-packages/omlx/models/vlm.py", line 286, in __call__
    result = self._language_model(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/omlx/HEAD-f6f4269/libexec/lib/python3.11/site-packages/mlx_vlm/models/qwen3_5/language.py", line 899, in __call__
    position_ids, rope_deltas = self.get_rope_index(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/omlx/HEAD-f6f4269/libexec/lib/python3.11/site-packages/mlx_vlm/models/qwen3_5/language.py", line 685, in get_rope_index
    spatial_merge_size = self.config.vision_config.spatial_merge_size
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VisionConfig' object has no attribute 'spatial_merge_size'
