### ISSUE TITLE
0.5.3 regression: MiniCPM-o-4_5 text-only chat fails with 'VisionConfig' object has no attribute 'spatial_merge_size' (regression of #241)

### ISSUE THREAD

**Issue by goldyard2022** [jundot/omlx#2387]
## Summary

MiniCPM-o-4_5 (`mlx-community/MiniCPM-o-4_5-5bit`) loads fine on 0.5.3 but every chat request — including **text-only** ones with no image attached — fails with:

```
RuntimeError: 'VisionConfig' object has no attribute 'spatial_merge_size'
```

This looks like a regression of #241, which was fixed in 4436306 back in March with exactly this diagnosis:

> MiniCPM-o reuses qwen3_vl's language model, which needs position state to be initialized before each forward pass. In standalone mlx-vlm this happens automatically through the full model call chain, but omlx was skipping that step for text-only requests.

The same code path is being hit again on 0.5.3.

## Environment

- oMLX **0.5.3** (Homebrew headless, `--with-custom-kernel`)
- mlx-lm 0.31.3 | mlx-vlm 0.6.3 | mlx 0.32.0
- macOS 26.5.2, M3 Ultra 512GB
- Model: `mlx-community/MiniCPM-o-4_5-5bit` (7.02GB, `model_type=minicpmo`)

## Reproduce

```
POST /v1/chat/completions
{"model": "MiniCPM-o-4_5-5bit", "max_tokens": 400,
 "messages": [{"role": "user", "content": "用一段话介绍你自己的能力。"}]}
```

No image attached. → HTTP 500.

Model settings: `trust_remote_code=true`, `max_context_window=40960`, `temperature=0.6` / `top_p=0.95` / `top_k=20`, all speculative paths off (`mtp_enabled`/`dflash_enabled`/`vlm_mtp_enabled`/`specprefill_enabled` = false), `turboquant_kv_enabled=false`.

## Load succeeds

```
omlx.engine.vlm   - VLMBatchedEngine loaded: .../MiniCPM-o-4_5-5bit
omlx.engine_pool  - Loaded model: MiniCPM-o-4_5-5bit
                    (actual: 6.99GB, estimated: 7.02GB, total: 14.54GB)
omlx.engine_pool  - Observed model load speed: 0.28s/GB (1.9s, 7.02GB)
```

## Traceback

```
File "omlx/engine/vlm.py", line 3174, in chat
File "omlx/engine/vlm.py", line 2954, in generate
File "omlx/engine_core.py", line 1292, in generate
File "omlx/engine_core.py", line 940, in generate
File "omlx/engine_core.py", line 66, in _raise_request_output_error
    raise RuntimeError(output.error)

# inner:
File "omlx/models/vlm.py", line 365, in __call__
    result = self._language_model(
File "mlx_vlm/models/qwen3_vl/language.py", line 585, in __call__
    position_ids, rope_deltas = self.get_rope_index(
File "mlx_vlm/models/qwen3_vl/language.py", line 303, in get_rope_index
    spatial_merge_size = self.config.vision_config.spatial_merge_size
AttributeError: 'VisionConfig' object has no attribute 'spatial_merge_size'
```

## Note

`mlx_vlm/models/minicpmo/config.py` `VisionConfig` (SigLIP-based) defines only:

```
model_type, hidden_size, intermediate_size, num_hidden_layers,
num_attention_heads, num_channels, image_size, patch_size,
hidden_act, layer_norm_eps, attention_dropout
```

There is no `spatial_merge_size` — that is a Qwen2/3-VL concept. So `qwen3_vl.language.get_rope_index` can never work against a minicpmo `VisionConfig` unless the position state is pre-initialized the way the #241 fix did it.

Related: #1314 reports the identical `AttributeError` for `MiniCPM-V-4.6-4bit` on 0.39-rc1 (still open, no comments) — possibly the same root cause.

**Comment by jundot** [comment]
Thanks for the detailed report, pointing at #241 saved me a lot of time. It is the same root cause coming back through a different path: the per-request mRoPE position dispatch added later routes MiniCPM-o around that #241 position-state init (mlx-vlm always injects mrope_section into minicpmo's text config, so omlx treats it as an mRoPE model), and the text-only prefill fallback then lets qwen3_vl's get_rope_index run against the SigLIP vision config. So this actually broke earlier than 0.5.3, and #1314 is very likely the same thing since minicpmv4_6 shares the structure. I applied the same position-state init to the fallback paths in 6e67f79 and verified both text-only and image chat work on MiniCPM-o-4_5-5bit. The fix will be in the next release.
