### ISSUE TITLE
0.7.0.dev4: Qwen3.8-Flash-Next (qwen4_exp) fails to load — "module 'custom_model' has no attribute 'ModelConfig'" (works on 0.7.0.dev2)

### ISSUE THREAD

**Issue by pierou** [jundot/omlx#3748]
0.7.0.dev4: Qwen3.8-Flash-Next (qwen4_exp) fails to load — "module 'custom_model' has no attribute 'ModelConfig'" (works on 0.7.0.dev2)

## Description

Upgrading from 0.7.0.dev2 to 0.7.0.dev4 breaks loading of
`pipenetwork/Qwen3.8-Flash-Next-MLX-mixed-4_8bit` (qwen4_exp architecture, 103.9 GB on disk,
PLE/mmap mode). The VLM engine load crashes inside mlx-vlm's `load_model`, the LLM
fallback is rejected by the custom-module (trust-remote-code) gate, and the model
stays unloadable: every chat completion returns 409. The same model, same settings,
same machine loads and runs fine on 0.7.0.dev2 (~20 tok/s decode).

The model directory ships its own `qwen4_exp.py` custom model module (no
`ModelConfig` class). oMLX's `omlx.patches.mlx_vlm_qwen4_exp_compat` patch **is
applied before the failure** (visible in the log), then mlx-vlm's generic loader
still tries `model_class.ModelConfig.from_dict(config)` on that module and crashes.

## To reproduce

1. Run oMLX 0.7.0.dev4 (mlx-vlm 0.7.1 @ 3fb24e9, mlx-lm 0.32.0 @ 872ae88,
   transformers 5.17.0) on macOS.
2. Load `pipenetwork/Qwen3.8-Flash-Next-MLX-mixed-4_8bit` (any qwen4_exp model with a
   custom module in the model dir should hit the same path).
3. Send any chat completion request.

## What happens

```
21:46:25,366 - omlx.patches.mlx_vlm_qwen4_exp_compat - INFO - Qwen4-Exp mlx-vlm compatibility patch applied
21:46:25,368 - omlx.patches.mlx_vlm_qwen4_exp_compat - INFO - Qwen4-Exp PLE mode for ...: mmap
21:46:25,430 - omlx.engine_pool - WARNING - VLM loading failed for Qwen3.8-Flash-Next-MLX-mixed-4_8bit,
             falling back to LLM: module 'custom_model' has no attribute 'ModelConfig'
21:46:25,463 - omlx.engine_pool - ERROR - Model load failed for 'Qwen3.8-Flash-Next-MLX-mixed-4_8bit';
             caching failure until next discovery refresh
  ...
  File ".../site-packages/mlx_vlm/utils.py", line 979, in load_model
    model_config = model_class.ModelConfig.from_dict(config)
AttributeError: module 'custom_model' has no attribute 'ModelConfig'
The above exception was the direct cause of the following exception:
RuntimeError: VLM load failed: module 'custom_model' has no attribute 'ModelConfig';
  LLM fallback also failed: The model at ... requires importing and running a custom
  module ('qwen4_exp.py') to build its architecture. This is disabled by default.
  Enable Trust Remote Code for this model if you trust it.
21:46:25,466 - omlx.server - WARNING - POST /v1/chat/completions → 409: Model
  'Qwen3.8-Flash-Next-MLX-mixed-4_8bit' failed to load: ...
```

## Expected behavior

The model loads as on 0.7.0.dev2 (VLM engine, PLE mmap), or at minimum the
qwen4_exp compat patch routes the load around the `ModelConfig` expectation for
models whose architecture module does not define one.

## Environment

- oMLX: 0.7.0.dev4 (regression vs 0.7.0.dev2, which works)
- mlx-vlm: 0.6.3 (dev2) → 0.7.1 (dev4); mlx-lm: 0.31.3 → 0.32.0; transformers: 5.12.1 → 5.17.0
- macOS 26.6.2 (Tahoe), Apple M2 Max / 96 GB, model loaded with PLE forced to
  SSD/mmap (oMLX's memory enforcer logs resident 111.5 GB against its 98.8 GB
  ceiling — same situation on dev2, not a factor)

## Notes

- Our crash is in mlx-vlm at the new pin: commit a1663771 ("feat: upgrade mlx-vlm
  and adapt cache and MTP integration", #3719) is absent from dev2, present in dev4,
  and bumps mlx-vlm 78b96eb → 3fb24e9 — the same upgrade that #3742 bisected as the
  cause of its MTP draft-acceptance regression.
- I did not test enabling "Trust Remote Code" for this model on dev4 (the 409
  text suggests the gate, but the primary crash is the AttributeError in the VLM
  path). Happy to test if it helps narrow this down.
- Full unedited server log available on request.

## Root cause (traced) + tested local fix

`get_model_and_args()` changed in mlx-vlm 0.7.x: when `config.json` declares
`model_file` **and** `model_path` is passed, it now imports that file as
`custom_model` and **bypasses the built-in registry** — and the new
`load_model` requires `custom_model.ModelConfig`. Published qwen4_exp
checkpoints ship `model_file=qwen4_exp.py` (exporting only `ModelArgs`-style
classes), so the load always dies on the new path. mlx-vlm 0.6.x had no
`model_file` resolution at all — `model_type: qwen4_exp` resolved to the
built-in `mlx_vlm.models.qwen4_exp`, which oMLX's compat patch explicitly
vendors and exposes ("Expose `mlx_vlm.models.qwen4_exp` from oMLX's vendor
tree") — which is why dev2 works.

Verified against the two pinned mlx-vlm checkouts and this model's real
config: unpatched 0.7.1 resolves to `custom_model` (no `ModelConfig`);
patched resolves to the vendored `mlx_vlm.models.qwen4_exp` and
`ModelConfig.from_dict()` succeeds. Minimal fix in
`omlx/patches/mlx_vlm_qwen4_exp_compat/__init__.py` — wrap
`mlx_vlm.utils.get_model_and_args` so that for `model_type == "qwen4_exp"`
`model_file` is dropped before resolution (restoring 0.6.x routing; only
`load_model` passes `model_path`, so the wrapper is surgical). With this
30-line patch the model loads and decodes at ~23.5 tok/s on dev4 (dev2:
~20 tok/s).

---
*This report was AI-assisted (drafted with the help of a coding agent from server
logs and reproduction steps; all log lines above are verbatim from the reported
environment).*

**Comment by pierou** [comment]
Root cause is above: mlx-vlm 0.7.x's `get_model_and_args()` gives a checkpoint's `config.json` `model_file` entry priority over the built-in registry and imports it as `custom_model` — then `load_model` requires `ModelConfig`, which the bundled `qwen4_exp.py` doesn't export.

**Workaround without any code change:** delete the `"model_file": "qwen4_exp.py"` line from the model's `config.json` (keep the file itself). Resolution then goes to the vendored `mlx_vlm.models.qwen4_exp` — the same path 0.7.0.dev2 used. Verified: with that key removed, `get_model_and_args(config, model_path=…)` resolves to the vendored module on 0.7.0.dev4 + mlx-vlm 0.7.1.

I've opened #3752 with a guarded fix (qwen4_exp only) plus a regression test; on this model dev4 loads and decodes ~23.5 tok/s after it (~20 on dev2, same machine: Apple M2 Max / 96 GB).

*(Same AI assistance applies to this comment as to the report.)*
