### ISSUE TITLE
[Regression] v0.6.3rc3: ANE tuning fails — 'verifyBundleAtPath: invalid model' (Code=10) at every bank split size

### ISSUE THREAD

**Issue by cropduster** [jundot/omlx#3124]
## Summary

After upgrading from v0.6.3rc2 to v0.6.3rc3, ANE tuning for my Qwen3.8-27B model fails during calibration. The fused procedure-bank compiler (`qwen35_ane_compile_linear_bank`) is rejected by Apple's ANE driver with `verifyBundleAtPath: invalid model` (Code=10) — and unlike the split-retry recovery documented in #2938, it fails at **every** bank size, not just the monolithic one.

## Environment

- Hardware: Mac Studio M4 Max, 128 GB
- macOS: 27.0
- oMLX: v0.6.3rc3 (build 2475)
- Model: `Qwen3.8-27B-oQ8e-fp16-mtp` (MLX oQ8e, fp16, mtp)

## Model settings (unchanged since v0.6.3rc2)

```json
{
  "qwen35_ane_prefill_enabled": true,
  "qwen35_ane_prefill_sequence_length": 2048,
  "qwen35_ane_prefill_fraction": 0.465,
  "qwen35_ane_prefill_fused_down": false,
  "qwen35_ane_prefill_max_layers": 64,
  "qwen35_ane_prefill_dual_ane": true,
  "qwen35_ane_prefill_gdn": true,
  "qwen35_ane_prefill_gdn_fraction": 0.45,
  "qwen35_ane_prefill_gdn_max_layers": 48,
  "qwen35_ane_prefill_cpu_enabled": true,
  "qwen35_ane_prefill_cpu_fraction": 0.1,
  "qwen35_ane_prefill_cpu_down_fraction": 0.15,
  "qwen35_ane_prefill_cpu_gdn_fraction": 0.1,
  "qwen35_ane_prefill_cpu_threads": 8
}
```

## Log evidence

The calibration bank here is small — 10 procedures, 1.20 GiB per instance — yet the split ladder fails identically at every size:

```
omlx.patches.qwen35_ane_prefill - WARNING - ANE procedure bank compilation failed (1 banks per instance, 10 procedures, 1.20 GiB per instance)
  RuntimeError: ANE procedure bank compilation failed: Error Domain=com.apple.appleneuralengine Code=10 "verifyBundleAtPath: invalid model"
omlx.patches.qwen35_ane_prefill - INFO - Retrying ANE procedure banks split at 819 MB per bank   → same error
omlx.patches.qwen35_ane_prefill - INFO - Retrying ANE procedure banks split at 409 MB per bank   → same error
omlx.patches.qwen35_ane_prefill - INFO - Retrying ANE procedure banks split at 204 MB per bank   → same error
omlx.patches.qwen35_ane_prefill - INFO - Retrying ANE procedure banks split at 102 MB per bank   → same error
omlx.patches.qwen35_ane_prefill - WARNING - Packed dual-ANE compilation failed; falling back to per-layer programs
omlx.admin.ane_tuning - ERROR - ANE tuning failed for Qwen3.8-27B-oQ8e-fp16-mtp
  RuntimeError: Representative ANE calibration bank could not be loaded
```

The benchmark profile then reports zero ANE operations:

```
[benchmark-ane-profile] pp=8193 category=gdn operations=0 configured_layers=0 ... ane0_duty=0.0000 ane1_duty=0.0000
```

## Why I think this differs from #2938

#2938 documents the monolithic 15 GiB bank failing with `0x20004` (Program load failure) and then **recovering** through the split-retry ladder. Here the failure is `verifyBundleAtPath: invalid model` (Code=10), an Apple bundle-verification rejection, and it reproduces at every split size down to 102 MB (8 banks) — so it does not look like the memory-driven case the ladder is designed to recover from.

## What changed

v0.6.3rc2 — still running at 2026-08-25 00:00, before the restart — compiled the same model fine through the per-procedure path:

```
omlx.patches.qwen35_ane_prefill - INFO - Eagerly compiled 64 MLP and 48 GDN procedures into 2 instance-pinned ANE programs (sequence_length=2048)
```

The failure appears only after the server restarted onto v0.6.3rc3 (build 2475, installed 08-24). The old per-procedure path (`qwen35_ane_compile_linear`) is still present in `qwen35_ane_prefill.py` (`_compile_pair` / `_compile_gdn`), but the tuner now goes exclusively through `_compile_dual_banks` → `qwen35_ane_compile_linear_bank`.

## Related

- #2938 — ANE disabled on oQ4e-mtp (0x20004 → split recovery)
- #2839 — ANE prefill not executing (0.6.2)
- #2908 — ANE Tuner V2 OOM at verification reload
- #3116 — 0.6.3rc3 tuner false-negative on single-ANE Mac

Happy to provide a full log excerpt or test specific bank sizes if that helps narrow it down.

**Comment by fxd0h** [comment]
Same failure on an M5 Max, macOS 27.0, rc3 built from source with `OMLX_WITH_CUSTOM_KERNEL=1`. It's not tuner-specific either. I just set `qwen35_ane_prefill_enabled` and sent a prefill, and got `verifyBundleAtPath: invalid model` (Code=10) at every split (1/2/5/9 banks), then the per-layer fallback fails the same way and it drops to Metal. Model here is a Qwen3.6-35B-A3B oQ4e.

Rebuilt rc2 on the same box, same model, and it compiles clean there: `Eagerly compiled 41 MLP and 30 GDN procedures`, no Code=10. So it repros on M5 Max and outside the tuner, and rc2 is fine here.

**Comment by beaglemoo** [comment]
Negative datapoint that may isolate this: **rc3 build 2475 compiles ANE banks cleanly on macOS 26.6.2.**

Same official DMG build as the reporter (0.6.3rc3, build 2475, macos26-27 artifact), M5 Pro 64 GB, macOS 26.6.2 (25G83), `Qwen3.8-27B-oQ4e-mtp`, fractions mlp 0.35 / gdn 0.45, dual-ANE on. Two separate cold loads earlier today:

```
Warmed 224 ANE procedures in 2.0s at load
Eagerly compiled 64 MLP and 48 GDN procedures into 2 instance-pinned ANE programs (sequence_length=2048)
```

No `verifyBundleAtPath`, no Code=10, no split ladder — first attempt succeeded both times, and prefill ran on the banks.

Lining that up with the two failing reports:

| Machine | macOS | oMLX | Result |
|---|---|---|---|
| M4 Max (reporter) | 27.0 | rc3 DMG build 2475 | Code=10 at every bank size |
| M5 Max (@fxd0h) | 27.0 | rc3 from source | Code=10 at every split; rc2 same box clean |
| M5 Pro (this) | **26.6.2** | rc3 DMG build 2475 | clean, 224 procedures |

So the failure does not track silicon generation (M4 Max and M5 Max both fail; an M5 works), does not track quant format (@fxd0h's is oQ4e like mine, the reporter's is oQ8e-fp16), and is not tuner-specific (@fxd0h reproduced it from a plain prefill). What it does track, on the data so far, is **rc3 code on macOS 27.0** — rc2 is fine on 27.0, rc3 is fine on 26.6.2, and only the intersection fails.

If that holds up with more reports, the question narrows to what changed in the bank compiler between rc2 and rc3 that macOS 27's ANE bundle validator rejects but 26's accepts. Happy to run any probe on the 26.6.2 side as a control — I can produce a known-good bundle from the same build number for comparison against a rejected one.

**Comment by idallasj** [comment]
I reproduced a related ANE failure on `v0.6.3rc3` and wanted to share a clean repro + environment details.

## Environment
- oMLX: `v0.6.3rc3`
- Hardware: Apple Silicon `M1 Ultra`
- OS: `macOS 27.0 beta (26A5421a)`
- Retest branch: `omlx-0.6.3rc3-retest`
- Retest commit: `636269b`
- Install method: verified-fresh DMG install

## Repro observation
- ANE compilation/tuning failure reproduces the same way after a fresh DMG install.
- This suggests install method is not the cause (in this environment).

## Scope of this report
At least in this setup, this is reproducible on a **macOS 27 beta** build.  
I’m not treating this as evidence of broad Apple Silicon/M1 Ultra incompatibility.

## Questions
- Is this currently expected on macOS 27 beta?
- Are there known flags/workarounds you want me to test?
- If useful, I can provide full logs and exact command sequence from this retest.

**Comment by jundot** [comment]
@cropduster @fxd0h @beaglemoo @idallasj Thanks for the detailed cross-version and OS reports. I traced this to rc3's ANE compile-cache change calling `setModelURL:` on `_ANEInMemoryModel`; macOS 27's per-file bundle hash verification rejects that caller-assigned staging URL with Code=10.

I fixed this on `main` in https://github.com/jundot/omlx/commit/7d77098ed83d7abcafeeaffaa4de1491820021d7. The fix leaves the framework-derived URL untouched in both cache modes, while cache-on still reuses Apple's content-hash cache through `compiledModelExists` and purges a failed cached model before retrying once.

I verified the native build and real per-layer/procedure-bank cache miss-to-hit behavior on macOS 26.5, and added regression coverage preventing `setModelURL:` from returning. I don't have a macOS 27 machine locally, so a retest on one of the affected systems would be appreciated.
