### ISSUE TITLE
[Bug] Engine crash during MTP verification with TurboQuant enabled ('TurboQuantMSEState' has no attribute 'ndim')

### ISSUE THREAD

**Issue by thkrmr** [jundot/omlx#2778]
# [Bug] Engine crash during MTP verification with TurboQuant enabled (`TurboQuantMSEState` has no attribute `ndim`)

### Describe the bug
In oMLX 0.6.1, sending a request to a Qwen3.6 MoE model with MTP and TurboQuant (KV Cache Quantization) enabled causes an immediate engine crash. **Note: This exact same configuration worked perfectly on oMLX 0.6.0.** The model only successfully generates on 0.6.1 if TurboQuant is manually disabled.

The issue stems from the new fused target-verification attention optimization introduced in 0.6.1. In `qwen35_verify_sdpa_split.py`, the `_eligible()` function checks `keys.ndim != 4`. However, when TurboQuant is active, `keys` is a custom `TurboQuantMSEState` object rather than a standard MLX array. Because `TurboQuantMSEState` does not expose an `ndim` attribute, it throws an `AttributeError` and halts the engine loop.

### Environment
- **oMLX Version:** 0.6.1 (Regression from 0.6.0)
- **OS:** macOS (Apple Silicon M1 Max, 32GB Unified Memory)
- **Model:** `Qwen3.6-35B-A3B-Uncensored-Genesis-Hermes-V6-dequantized-oQ3e-mtp`
- **Settings:** TurboQuant (KV Cache Quantization) enabled

### Steps to Reproduce
1. Start oMLX `0.6.1` with the model above (or any Qwen 3.5/3.6 model that supports MTP).
2. Ensure TurboQuant (KV Cache Quantization) is enabled.
3. Send a prompt to the model.
4. The generation fails immediately with `status='failed'` due to an engine loop error. (Turning TurboQuant OFF bypasses the bug).

### Stack Trace
```python
2026-08-18 00:23:11,548 - omlx.scheduler - INFO - [-] - TurboQuant: converted 9/40 cache layers to 4.0-bit, skipped last KVCache layer
...
2026-08-18 00:23:14,216 - omlx.patches.qwen35_gdn_prework - INFO - [-] - [gdn-prework] fused verify prework engaged (S=4)
2026-08-18 00:23:14,225 - omlx.engine_core - ERROR - [-] - Engine loop error: 'TurboQuantMSEState' object has no attribute 'ndim'
Traceback (most recent call last):
  File "/Applications/oMLX.app/Contents/Resources/omlx/engine_core.py", line 394, in _engine_loop
    step_outputs = await loop.run_in_executor(
...
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_vlm/models/qwen3_5/language.py", line 1483, in __call__
    output = _target_verify_left_padded_attention(
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/qwen35_verify_sdpa_split.py", line 132, in patched_target_verify_attention
    limit = _eligible(queries, keys, cache)
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/qwen35_verify_sdpa_split.py", line 78, in _eligible
    if queries.ndim != 4 or keys.ndim != 4:
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_vlm/turboquant.py", line 4953, in __getattr__
    return getattr(self._state, name)
AttributeError: 'TurboQuantMSEState' object has no attribute 'ndim'
```

### Possible Solution
Update `_eligible()` in `qwen35_verify_sdpa_split.py` to correctly handle `TurboQuantMSEState` objects (e.g., checking if the object is quantized before checking dimensions, or exposing the underlying tensor's dimensions safely).

### Workaround
Disabling KV Cache Quantization (TurboQuant) in the oMLX server settings prevents `keys` from being compressed into a `TurboQuantMSEState` object. The cache remains as a standard tensor, allowing the new MTP verification logic to process correctly without crashing.

**Comment by aaramos** [comment]
Fix + regression test up in #2782 — `_eligible()` needs to tolerate an object without `.ndim` (the turboquant proxy) the same way it already tolerates other quantized caches via the `hasattr(cache, "bits")` check, instead of raising before that check runs.

**Comment by VictorLowther** [comment]
Same.  Complete session with all logs:

2026-08-17 14:20:55,046 - omlx.engine_pool - INFO - [-] - Loading model: Qwen3.8-27B-oQ8e-mtp
2026-08-17 14:20:55,046 - omlx.patches.mlx_lm_mtp.nemotron_h_chain - INFO - [-] - nemotron_h MTP chain patch applied (depth-k drafting, sequential fused verify, replay-free rollback)
2026-08-17 14:20:55,046 - omlx.utils.model_loading - INFO - [-] - Speculative backend selected for /Users/victor/.omlx/models/Qwen3.8-27B-oQ8e-mtp: Lightning MTP (model_type=qwen3_5, active)
2026-08-17 14:20:55,047 - omlx.utils.model_loading - INFO - [-] - mlx-vlm MTP sanitize patch applied for /Users/victor/.omlx/models/Qwen3.8-27B-oQ8e-mtp
2026-08-17 14:20:55,047 - omlx.utils.model_loading - INFO - [-] - mlx-vlm runtime MTP patch applied for /Users/victor/.omlx/models/Qwen3.8-27B-oQ8e-mtp
2026-08-17 14:20:56,160 - omlx.engine.vlm - INFO - [-] - Vision feature cache enabled (SSD: /Users/victor/.omlx/cache/vision_features)
2026-08-17 14:20:57,202 - omlx.scheduler - INFO - [-] - Loaded 1 additional EOS token(s) from generation_config.json: {248044}
2026-08-17 14:20:57,202 - omlx.scheduler - INFO - [-] - Enlarging paged cache block_size=256 to 2048 for ArraysCache hybrid model (reduces boundary snapshot overhead)
2026-08-17 14:20:57,202 - omlx.memory_monitor - INFO - [-] - MemoryMonitor initialized (estimator-only, eviction disabled)
2026-08-17 14:20:57,202 - omlx.memory_monitor - INFO - [-] - Model info set: 64 layers (16 KVCache), 4 KV heads, 24 Q heads, 256 head_dim. Estimated memory per 64-token block: 16.00 MB
2026-08-17 14:20:57,202 - omlx.scheduler - INFO - [-] - paged SSD-only mode: max_blocks=100000, block_size=2048 tokens
2026-08-17 14:20:57,202 - omlx.cache.paged_cache - INFO - [-] - PagedCacheManager initialized: block_size=2048, initial_blocks=256, max_blocks=100000, max_tokens=204800000
2026-08-17 14:20:57,203 - omlx.cache.paged_ssd_cache - INFO - [-] - Scanning SSD cache directory: /Users/victor/.omlx/cache
2026-08-17 14:20:57,761 - omlx.cache.paged_ssd_cache - INFO - [-] - SSD cache scan complete: scanned=2698, indexed=1343, errors=0, total_size=371.88 GB, gdn_sidecars=0, skipped_incompatible=1354 blocks (128.50 GB)
2026-08-17 14:20:57,762 - omlx.cache.paged_ssd_cache - INFO - [-] - PagedSSDCacheManager initialized: dir=/Users/victor/.omlx/cache, max_size=372.00 GB, hot_cache=10.00 GB, existing_files=1343, disk_free=2708.36 GB, cache_used=371.88 GB, incompatible_files=1354
2026-08-17 14:20:57,762 - omlx.cache.paged_cache - INFO - [-] - paged SSD cache manager connected to PagedCacheManager
2026-08-17 14:20:57,762 - omlx.cache.prefix_cache - INFO - [-] - PagedSSDCacheManager connected to BlockAwarePrefixCache
2026-08-17 14:20:57,762 - omlx.scheduler - INFO - [-] - paged SSD cache enabled: cache_dir=/Users/victor/.omlx/cache, max_size=372.00 GB, block_size=2048 tokens
2026-08-17 14:20:57,762 - omlx.scheduler - INFO - [-] - paged SSD cache enabled: /Users/victor/.omlx/cache, block_size=2048, max_blocks=100000
2026-08-17 14:20:57,762 - omlx.engine_core - INFO - [-] - Engine started
2026-08-17 14:20:57,769 - omlx.memory_monitor - INFO - [-] - Model info set: 64 layers (16 KVCache), 4 KV heads, 24 Q heads, 256 head_dim. Estimated memory per 64-token block: 4.81 MB
2026-08-17 14:20:57,769 - omlx.engine.vlm - INFO - [-] - TurboQuant KV cache enabled for VLM: 4.0 bits
2026-08-17 14:20:57,769 - omlx.patches.qwen35_fa256_attention - INFO - [-] - Qwen FA-256 steel patch skipped: NAX GPU, stock SDPA is faster
2026-08-17 14:20:57,770 - omlx.cache.paged_ssd_cache - INFO - [-] - PagedSSDCacheManager updated layer cache signature (64 layers, 3 unique types, turboquant_kv_bits=4.0, cachelist_subtypes=no)
2026-08-17 14:20:57,778 - omlx.cache.paged_ssd_cache - INFO - [-] - Invalidated 4 SSD index entries with stale layer cache signature for model 'Qwen3.8-27B-oQ8e-mtp' (kept 1339)
2026-08-17 14:20:57,822 - omlx.engine.vlm - INFO - [-] - VLM tool calling enabled: parser=qwen3_coder
2026-08-17 14:20:57,825 - omlx.engine.vlm - INFO - [-] - VLMBatchedEngine loaded: /Users/victor/.omlx/models/Qwen3.8-27B-oQ8e-mtp
2026-08-17 14:20:57,827 - omlx.engine_pool - INFO - [-] - Loaded model: Qwen3.8-27B-oQ8e-mtp (actual: 28.20GB, local estimate: 29.34GB, full model: 29.34GB, total: 29.34GB)
2026-08-17 14:20:57,827 - omlx.admin.benchmark - INFO - [-] - Benchmark: loaded Qwen3.8-27B-oQ8e-mtp
2026-08-17 14:21:00,563 - omlx.scheduler - INFO - [-] - TurboQuant: converted 15/64 cache layers to 4.0-bit, skipped last KVCache layer
2026-08-17 14:21:00,821 - omlx.patches.mlx_lm_mtp.batch_generator - INFO - [-] - MTP path activated for uid=0 (model has mtp_forward, batch=1, primed=2049)
2026-08-17 14:21:00,926 - omlx.engine_core - ERROR - [-] - Engine loop error: 'TurboQuantMSEState' object has no attribute 'ndim'
Traceback (most recent call last):
  File "/Applications/oMLX.app/Contents/Resources/omlx/engine_core.py", line 394, in _engine_loop
    step_outputs = await loop.run_in_executor(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/cpython-3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/engine_core.py", line 368, in _step_burst
    outputs.append(self.scheduler.step())
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/scheduler.py", line 11485, in step
    responses = list(self.batch_generator.next_generated())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_lm/generate.py", line 1866, in next_generated
    prompt_responses, generation_responses = self._next()
                                             ^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_lm_mtp/batch_generator.py", line 275, in patched_bg_next
    return original_bg_next(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_lm/generate.py", line 1775, in _next
    generation_responses = self._generation_batch.next()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_lm_mtp/batch_generator.py", line 187, in patched_next
    return _mtp_next(self, state)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_lm_mtp/batch_generator.py", line 2652, in _mtp_next
    _run_verify_cycle(gen_batch, state)
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_lm_mtp/batch_generator.py", line 2745, in _run_verify_cycle
    return _run_verify_cycle_chain(gen_batch, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_lm_mtp/batch_generator.py", line 2787, in _run_verify_cycle_chain
    logits, hidden, gdn_states = _call_backbone(
                                 ^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_lm_mtp/batch_generator.py", line 1415, in _call_backbone
    result = model(inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/models/vlm.py", line 355, in __call__
    result = self._language_model(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_vlm_mtp/qwen35_vlm_runtime.py", line 330, in __call__
    out = original_call(
          ^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_vlm/models/qwen3_5/language.py", line 2558, in __call__
    out = self.model(
          ^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_vlm_mtp/qwen35_vlm_runtime.py", line 417, in __call__
    out = original_call(
          ^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_vlm/models/qwen3_5/language.py", line 1913, in __call__
    h = layer(
        ^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_vlm/models/qwen3_5/language.py", line 1760, in __call__
    r = self.self_attn(
        ^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_vlm/models/qwen3_5/language.py", line 1483, in __call__
    output = _target_verify_left_padded_attention(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/qwen35_verify_sdpa_split.py", line 132, in patched_target_verify_attention
    limit = _eligible(queries, keys, cache)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/qwen35_verify_sdpa_split.py", line 78, in _eligible
    if queries.ndim != 4 or keys.ndim != 4:
                            ^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_vlm/turboquant.py", line 4953, in __getattr__
    return getattr(self._state, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TurboQuantMSEState' object has no attribute 'ndim'

2026-08-17 14:21:00,928 - omlx.admin.benchmark - ERROR - [-] - Benchmark error: 'TurboQuantMSEState' object has no attribute 'ndim'
Traceback (most recent call last):
  File "/Applications/oMLX.app/Contents/Resources/omlx/admin/benchmark.py", line 1693, in run_benchmark
    async for _ in engine.stream_generate(
  File "/Applications/oMLX.app/Contents/Resources/omlx/engine/vlm.py", line 3436, in stream_generate
    async for output in engine.stream_outputs(request_id):
  File "/Applications/oMLX.app/Contents/Resources/omlx/engine_core.py", line 1372, in stream_outputs
    async for output in self.engine.stream_outputs(request_id, timeout):
  File "/Applications/oMLX.app/Contents/Resources/omlx/engine_core.py", line 941, in stream_outputs
    _raise_request_output_error(output)
  File "/Applications/oMLX.app/Contents/Resources/omlx/engine_core.py", line 79, in _raise_request_output_error
    raise RuntimeError(output.error)
RuntimeError: 'TurboQuantMSEState' object has no attribute 'ndim'
2026-08-17 14:21:00,929 - omlx.engine_pool - INFO - [-] - Unloading model: Qwen3.8-27B-oQ8e-mtp (immediate abort)
2026-08-17 14:21:00,929 - omlx.engine_core - INFO - [-] - Engine stopped
2026-08-17 14:21:00,936 - omlx.scheduler - INFO - [-] - Scheduler shutdown initiated...
2026-08-17 14:21:00,938 - omlx.cache.paged_ssd_cache - INFO - [-] - Shutting down PagedSSDCacheManager...
2026-08-17 14:21:00,938 - omlx.scheduler - INFO - [-] - Scheduler shutdown completed
2026-08-17 14:21:00,938 - omlx.cache.paged_cache - INFO - [-] - PagedCacheManager cleared (reset to 256 initial blocks)
2026-08-17 14:21:01,016 - omlx.scheduler - INFO - [-] - Deep reset completed - all caches cleared
2026-08-17 14:21:01,064 - omlx.engine.vlm - INFO - [-] - VLMBatchedEngine stopped
2026-08-17 14:21:01,147 - omlx.engine_pool - INFO - [-] - Unloaded model: Qwen3.8-27B-oQ8e-mtp, freed=32.15GB (expected>=27.34GB), active_memory: 515.08KB (settled)
