### ISSUE TITLE
Can't get MCP to work

### ISSUE THREAD

**Issue by zulufoxtrot** [jundot/omlx#71]
**Describe the bug**

I have set up an MCP server, but I can't get any model to use it through oMLX.
I honestly don't know if it's a problem with oMLX, the model, this MCP, or a user error.

This my mcp.json:

```json
{
  "mcpServers": {
    "brave-search": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-brave-search"
      ],
      "env": {
        "BRAVE_API_KEY": "xxx"
      }
    }
  }
}
```

When I ask for instance Qwen3.5-122B-A10B-4bit to use it, it denies having access to it, even if i specifically mention "use the Brave MCP to search online".

The path to mcp.json is correct in oMLX settings.

**Comment by jundot** [comment]
Thanks for reporting this. I looked into it and found the root cause.
The mcp tools from your config are loaded correctly, but they are not being passed to the model during chat completions. So the model genuinely has no idea the tools exist. This is a server side bug, not an issue with your setup or model choice.
Will be fixed in the next release.

**Comment by zulufoxtrot** [comment]
Awesome!

**Comment by jundot** [comment]
This has been fixed in [v0.2.2](https://github.com/jundot/omlx/releases/tag/v0.2.2). The MCP tools are now automatically injected into chat completion requests, so the model will be aware of them.

If you're using the macOS menubar app, auto-update checks once per day due to GitHub rate limit concerns, so it may not show up immediately. You can grab the latest DMG from the [release page](https://github.com/jundot/omlx/releases/tag/v0.2.2) if you want to update right away.

Let me know if it works for you!

**Comment by zulufoxtrot** [comment]
Thanks! I removed the menubar app and i'm now using just the service.
The update has not propagated to the brew registry yet. ⌛ 
edit: had to run `brew update` beforehand. 😅

**Comment by zulufoxtrot** [comment]
Unfortunately, I'm still unable to use MCPs.

I must preface this by saying i don't fully understand the MCP architecture. I read that they are supposed to be run locally (called directly by the client) but then I don't understand why or how LLM runners accept MCP declarations if they can't use them.

I did restart oMLX before testing.

<img width="892" height="416" alt="Image" src="https://github.com/user-attachments/assets/ed29dbbe-22ce-4d71-8d29-3f464ec993b5" />

The model stops responding at the step where it's supposed to make the tool call.

I didn't see any relevant logs during tool calling.

Startup logs:

```
2026-03-04 15:27:35,219 - omlx.mcp.config - INFO - [-] - Loading MCP config from: /Users/xxx/.lmstudio/mcp.json
2026-03-04 15:27:35,219 - omlx.mcp.manager - INFO - [-] - Starting MCP client manager with 5 servers
2026-03-04 15:27:35,326 - omlx.mcp.client - ERROR - [-] - Failed to connect to MCP server 'git': [Errno 2] No such file or directory: 'uvx'
2026-03-04 15:27:35,328 - omlx.mcp.client - ERROR - [-] - Failed to connect to MCP server 'fetch': [Errno 2] No such file or directory: 'uvx'
2026-03-04 15:27:38,506 - omlx.mcp.client - INFO - [-] - Connected to MCP server 'brave-search' (2 tools available)
2026-03-04 15:27:40,143 - omlx.mcp.client - INFO - [-] - Connected to MCP server 'memory' (9 tools available)
2026-03-04 15:27:40,372 - omlx.mcp.client - ERROR - [-] - Failed to connect to MCP server 'filesystem': Connection closed
2026-03-04 15:27:40,373 - omlx.mcp.manager - INFO - [-] - Connected to 'memory'
2026-03-04 15:27:40,373 - omlx.mcp.manager - INFO - [-] - Connected to 'brave-search'
2026-03-04 15:27:40,373 - omlx.mcp.manager - INFO - [-] - MCP manager started: 2/5 servers, 11 tools available
```

There is another issue: It says it can't find `uvx`, but it is there and present in $PATH:

```
 xxx@studio  ~/.lmstudio  which uvx
/Users/xxx/.local/bin/uvx
```

My updated mcp.json:

```json
{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "/mnt/ssd4to"]
    },
    "git": {
      "command": "uvx",
      "args": ["mcp-server-git"]
    },
      "fetch": {
        "command": "uvx",
        "args": ["mcp-server-fetch"]
      },
    "memory": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-memory"
      ]
    },
    "brave-search": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-brave-search"
      ],
      "env": {
        "BRAVE_API_KEY": "xxxx"
      }
    }
  }
}
```

**Comment by zulufoxtrot** [comment]
Interestingly, oMLX failed to save history for my last 2 messages:

<img width="887" height="419" alt="Image" src="https://github.com/user-attachments/assets/3e7b5ada-a566-4407-a01c-64bcf4f08a39" />

I'm guessing the tool call failed in a way that prevented them from being saved.

edit: when asking to use tools, oMLX just returns an empty body response to the POST /completions request.

**Comment by jundot** [comment]
<img width="528" height="130" alt="Image" src="https://github.com/user-attachments/assets/7363bf4f-6f86-432a-8191-c0d1c012e31b" />

The MCP tool injection into chat completions is now working correctly in v0.2.2. The model receives the tool definitions and generates proper tool calls.

However, looking at your screenshot, it seems like the client you're using doesn't handle the tool execution loop. When the model returns a tool_calls response, the client needs to:
  1. Execute the tool (either locally or via oMLX's /v1/mcp/execute endpoint)
  2. Append the tool result to the conversation
  3. Send a follow-up chat completion request

The built-in "Chat with oMLX" interface is intended for basic functionality testing and does not implement this client-side tool execution loop. I'd recommend using a client that supports OpenAI-compatible tool calling, such as Open WebUI.

Regarding the uvx not found error: this is a common macOS issue where services don't inherit your shell's $PATH. You can work around it by using the full path (e.g., /Users/xxx/.local/bin/uvx) in your mcp.json instead of just uvx.

**Comment by zulufoxtrot** [comment]
Thanks. My responses below:

> The MCP tool injection into chat completions is now working correctly in v0.2.2

Cool. I've had problems with the mcp package but it is already addressed in another issue.

> You can work around it by using the full path (e.g., /Users/xxx/.local/bin/uvx) in your mcp.json instead of just uvx.

Done ✅ seems to have fixed it

> I'd recommend using a client that supports OpenAI-compatible tool calling, such as Open WebUI.

Aside from the screenshots, my main clients are Kilo Code and AnythingLLM.
I just checked and it seems like it AnythingLLM doesn't support the OpenAI format for tools? https://github.com/Mintplex-Labs/anything-llm/issues/4181
Maybe I can work around it by using the Anthropic API endpoints?
I'm 90% sure Kilo supports OpenAI tool calls though.
Maybe I should just use OpenWebUI?

Sorry for all the questions, I'm kinda new to this.

**Comment by William12556** [comment]
I am also experiencing this issue and wanted to share my environment and diagnostic findings in case they are useful.

**Environment**
- Hardware: Apple M4 Mac Mini, 64GB unified memory
- oMLX: current release
- Models tested: Devstral-Small-2-24B-Instruct-2512, Llama-3.2-3B-Instruct-4bit
- Client: Open WebUI
- MCP servers configured: `filesystem` (18 tools), `mcp-grep` (1 tool)

**Observed behaviour**

MCP initialisation succeeds at startup — the log confirms 19 tools available:

```
omlx.mcp.manager - INFO - MCP manager started: 2/2 servers, 19 tools available
omlx.server     - INFO - MCP initialized with 19 tools
```

Chat completions complete successfully for both models. However, no tool dispatch or tool result log entries appear from `omlx.mcp.client` after any completion. Tools are never executed regardless of model.

With Devstral, tool calls appear in the `content` field in Mistral plain-text format with `tool_calls: null`. With Llama 3.2, which natively emits OpenAI-format `tool_calls`, the result is identical — no tool dispatch occurs.

**Conclusion from logs**

MCP connects and advertises tools correctly, but tool execution does not appear to be wired into the chat completion path in the current release. The issue reproduces across both Mistral-format and OpenAI-format tool call outputs.

Happy to provide additional log output if it would help. 
Thank you.

**Comment by jundot** [comment]
I'll look into this more for the next release. Thanks for the update.

**Comment by epicycle** [comment]
Does anyone know if MCPs are working with oMLX yet or not? Was hoping on starting to setup web search but before I do I was trying to find docs and ran into this issue. Does it not work?

**Comment by jundot** [comment]
Sorry for the late reply on this.

Just merged #286 which adds streamable-http transport for MCP connections. This doesn't directly fix the issue here but it's part of ongoing MCP improvements. Will be included in the next release.

To clarify the current state: MCP tool injection and tool_calls parsing have been working since v0.2.2. The server returns tool_calls in OpenAI-compatible format, and the `/v1/mcp/execute` endpoint is available for executing them. The tool execution loop itself is client-side responsibility, same as OpenAI/Anthropic APIs.

@epicycle yes MCP works. You need a client that supports OpenAI tool calling (Open WebUI, etc.). The flow is: model returns tool_calls → client executes via `/v1/mcp/execute` → client appends result → client sends follow-up request.

@William12556 if Open WebUI isn't dispatching tool calls, it might be a format mismatch between what oMLX returns and what Open WebUI expects. Could you share the raw response body from a completion that includes tool_calls? That would help me check if the format is off.

Closing this for now since the original issue (tools not injected) was fixed in v0.2.2. If you run into problems with tool calling on specific clients like Open WebUI, feel free to reopen or file a new issue with the raw response details.
