### ISSUE TITLE
0.6.1 Lightning MTP verify-split crashes on TurboQuant KV: TurboQuantMSEState has no attribute ndim

### ISSUE THREAD

**Issue by cyhsieh817** [jundot/omlx#2784]
## Summary

After upgrading to **oMLX 0.6.1**, generating with **Lightning MTP + TurboQuant KV** on a Qwen3.8 / `qwen3_5` VLM checkpoint fails immediately:

```
Error: 'TurboQuantMSEState' object has no attribute 'ndim'
```

The same checkpoint and the same two settings worked on **0.6.0** (long tool-call sessions on 2026-08-17 through 2026-08-18 02:54). The weights still load; the crash is in the new target-verify attention path.

Related but not the same: #2133 (0.5.0-dev2: TurboQuant unavailable when native MTP is on). This report is a hard crash after 0.6.1, not a UI/toggle issue.

## Environment

- oMLX **0.6.1** (`brew`, `jundot/omlx/omlx`)
- macOS Apple Silicon
- Model: `Youssofal/Qwen3.8-27B-MTPLX-Optimized-Speed` (`model_type=qwen3_5`, Lightning MTP selected at load)
- Settings that crash: `mtp_enabled: true` **and** `turboquant_kv_enabled: true` (`turboquant_kv_bits: 4`, `turboquant_skip_last: true`)
- Log around the first failure:
  - `Speculative backend selected … Lightning MTP (model_type=qwen3_5, active)`
  - `MTP path activated … batch=1`
  - `[gdn-prework] fused verify prework engaged (S=4)`
  - then the AttributeError

## Reproduction

1. Load a Qwen3.8 / `qwen3_5` checkpoint that uses Lightning MTP.
2. Enable **both** Lightning MTP and TurboQuant KV (4-bit).
3. Send any chat completion that reaches decode / MTP verify (a short prompt is enough).

Happened three times in a row (09:09, 09:11, 09:16 local) with the same traceback.

## Traceback (trimmed)

```
File "…/omlx/patches/mlx_lm_mtp/batch_generator.py", line 2745, in _run_verify_cycle
    return _run_verify_cycle_chain(gen_batch, state)
File "…/omlx/patches/qwen35_verify_sdpa_split.py", line 132, in patched_target_verify_attention
    limit = _eligible(queries, keys, cache)
File "…/omlx/patches/qwen35_verify_sdpa_split.py", line 78, in _eligible
    if queries.ndim != 4 or keys.ndim != 4:
File "…/mlx_vlm/turboquant.py", line 4953, in __getattr__
    return getattr(self._state, name)
AttributeError: 'TurboQuantMSEState' object has no attribute 'ndim'
```

## Cause

`qwen35_verify_sdpa_split.py` (new in 0.6.1, PR #2751 family) wraps `_target_verify_left_padded_attention`. Its module docstring already says quantized caches should fall through to the original implementation. `_eligible()` is supposed to reject those cases via `hasattr(cache, "bits")`, but it reads `keys.ndim` **first**:

```python
def _eligible(queries, keys, cache) -> int:
    if queries.ndim != 4 or keys.ndim != 4:  # line 78
        return 0
    …
    if cache is not None and hasattr(cache, "bits"):
        return 0
```

With TurboQuant KV on, `keys` is a `_QuantizedStateProxy` around `TurboQuantMSEState` (`NamedTuple` of `norms` / `indices`). The proxy only defines `.shape`; `__getattr__` forwards `ndim` to the NamedTuple and raises. The `bits` check never runs.

## Workaround (confirmed)

Set `turboquant_kv_enabled: false` on that model, keep `mtp_enabled: true`, restart.

After that:

- Lightning MTP still selected
- `[verify-split] hd-256 causal vector attention engaged (q_len=4/3/2)`
- completion succeeds (`finish_reason=stop`)

Disabling TurboQuant invalidates the SSD prefix-cache signature (expected).

## Suggested fix

Guard `_eligible` before touching `.ndim`, so the documented fallback actually runs:

```python
def _eligible(queries, keys, cache) -> int:
    if not hasattr(queries, "ndim") or not hasattr(keys, "ndim"):
        return 0
    if queries.ndim != 4 or keys.ndim != 4:
        return 0
    …
```

or `isinstance(..., mx.array)`.

That should restore the 0.6.0 combination: Lightning MTP + TurboQuant KV, with quantized caches staying on the original verify path.

**Comment by zesming** [comment]
Confirmed on an M4 Pro 64 GB with a Qwen3.8-27B oQ4e VLM: the merged fix in #2782 resolves this exact 0.6.1 regression while keeping both TurboQuant KV4 and Lightning MTP active. Text and image requests completed; MTP accepted draft tokens in both paths. Full end-to-end measurements are posted at https://github.com/jundot/omlx/pull/2782#issuecomment-5322874355.

The released 0.6.1 app still contains the crashing direct `.ndim` access, so users need the next build/hotfix or should keep TurboQuant disabled while retaining MTP.

**Comment by 0902horn** [comment]
Also hitting this on **0.6.1** (Qwen3.8-27B, `qwen3_5`, MTP + TurboQuant 4-bit).
PR #2782 fixed the crash itself, so this is just to document **why the crash is
intermittent** — we spent a while believing some checkpoints were immune
(a mixed 4/5-bit oQ4e build "never crashed" for days), and the reason turned out
to be unrelated to the weights:

## Two wrappers, one function, load-order race

Both of these monkey-patch the same mlx-vlm function
`qwen3_5.language._target_verify_left_padded_attention`:

1. `omlx/patches/turboquant_attention.py :: _patch_vlm_target_verify_attention()`
   (the TurboQuant-safe dispatcher, fixes #2139) — applied from
   `apply_turboquant_attention_patch()`, which has **two call sites**:
   `engine/vlm.py:1764` and `engine/batched.py:335`;
2. `omlx/patches/qwen35_verify_sdpa_split.py :: apply_qwen35_verify_sdpa_split_patch()`
   — applied at `engine/vlm.py:1819` during model load.

Whichever applies **last** becomes the outermost wrapper:

- **tq-safe outermost** → TurboQuant caches are intercepted and routed to the TQ
  kernel before verify-split ever sees them. Session works.
- **verify-split outermost** → `_eligible()` runs first on the TurboQuant
  proxy/state → the `keys.ndim` dereference raises → every MTP verify cycle dies
  → 500 on every request. Session is broken from the first request.

The dual call sites for `apply_turboquant_attention_patch()` mean whichever
engine path loads the first TQ model decides the order, so it can flip between
restarts. That's the whole "sometimes it works" mystery.

## Evidence (instrumented both wrappers, same install)

```
# apply order flipped across restarts (server log timeline):
session A:  [APPLY tq_safe] 22:44:59.252 → [split applied] 22:44:59.424   (split outermost → crashes)
session B:  split applied during engine load, tq_safe already applied       (tq_safe outermost → works)

# type flow in a split-outermost session, first call per signature:
[split_patched]   keys=_QuantizedStateProxy cache=TurboQuantKVCache mask=str qlen=4
[tq_safe_patched] keys=_QuantizedStateProxy cache=TurboQuantKVCache mask=str qlen=4
[split_patched]   keys=array                cache=KVCache          mask=str qlen=4
```

The third line shows the crash is not about "some checkpoints don't reach this
path": in a split-outermost session the previously-"immune" mixed-precision
checkpoint hits the exact same `_QuantizedStateProxy` at the exact same gate —
it had simply always been run in tq_safe-outermost sessions.

## Local workaround used on 0.6.1 (before noticing #2782)

Same idea as the merged fix — guard `_eligible()` against non-tensor states:

```diff
@@ def _eligible(queries, keys, cache) -> int:
     """Return the vector-kernel row limit (>0) when this call is ours."""
+    # Guard non-tensor states (TurboQuant proxies/states) before .ndim
+    if not (hasattr(queries, "ndim") and hasattr(keys, "ndim")):
+        return 0
     if queries.ndim != 4 or keys.ndim != 4:
         return 0
```

This is order-independent: verify-split declines, the inner tq-safe wrapper
handles the call. Verified with both patch orders, two 27B checkpoints, TQ4+MTP
co-enabled (MTP accept 75–92%, verify-split still engages on non-TQ layers).

## Suggestion

The crash fix is in, but the **order race between the two wrappers** is still
latent on main. If it's cheap to do, installing the wrappers in a deterministic
order (e.g. verify-split first, so tq-safe is always outermost), or having
`apply_qwen35_verify_sdpa_split_patch()` decline when
`_omlx_tq_target_verify_patched` is already set, would remove the class of bug
entirely. For anyone still on 0.6.1: upgrading to 0.6.2+ resolves this.

---

*Context for anyone finding this later: reproduced on 0.6.1, macOS 26.5, M4 Max
64 GB, two qwen3_5 checkpoints (full 4-bit and mixed 4/5-bit); ~half of server
sessions crashed on every request, the other half were stable, per the race above.*
