### ISSUE TITLE
Whisper broke in 0.3.8

### ISSUE THREAD

**Issue by fingon** [jundot/omlx#1072]
**Describe the bug**

 transformers 5.8.0  expects mistral-common[image]>=1.10.0, but the environment has mistral-common 1.9.1, which lacks ReasoningEffort.

**To Reproduce**

Fire up e.g. whisper-3-large-turbo.

The error message is misleading:
```
2026-05-02 14:12:09,074 - omlx.server - WARNING - [-] - POST /v1/audio/transcriptions → 500: STT model '/Users/mstenber/.omlx/models/whisper-large-v3-turbo' is missing the HuggingFace processor / feature-extractor configuration (preprocessor_config.json and/or tokenizer files). MLX-converted repositories sometimes omit these. Fix: either use an HF-compatible variant of the model or copy preprocessor_config.json, tokenizer.json and special_tokens_map.json from the upstream HuggingFace repo into the local model directory.
```
(the files are there)

You get interesting backtrace if you run instead this:
```
uv run --extra audio python -c 'from transformers import WhisperProcessor;WhisperProcessor.from_pretrained("your-path/models/whisper-large-v3-turbo")'
```

which looks like this:
```
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/processing_utils.py", line 1430, in from_pretrained
    return cls.from_args_and_dict(args, processor_dict, **instantiation_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/processing_utils.py", line 1197, in from_args_and_dict
    processor = cls(*args, **valid_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/models/whisper/processing_whisper.py", line 25, in __init__
    super().__init__(feature_extractor, tokenizer)
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/processing_utils.py", line 628, in __init__
    self.check_argument_for_proper_class(attribute_name, arg)
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/processing_utils.py", line 706, in check_argument_for_proper_class
    proper_class = tuple(self.get_possibly_dynamic_module(n) for n in class_name if n is not None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/processing_utils.py", line 706, in <genexpr>
    proper_class = tuple(self.get_possibly_dynamic_module(n) for n in class_name if n is not None)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/processing_utils.py", line 1594, in get_possibly_dynamic_module
    if hasattr(transformers_module, module_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 2226, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 2460, in _get_module
    raise e
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 2458, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mstenber/.local/share/uv/python/cpython-3.12.13-macos-aarch64-none/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/transformers/tokenization_mistral_common.py", line 42, in <module>
    from mistral_common.protocol.instruct.request import ChatCompletionRequest, ReasoningEffort
ImportError: cannot import name 'ReasoningEffort' from 'mistral_common.protocol.instruct.request' (/Users/mstenber/share/1/git/omlx/.venv/lib/python3.12/site-packages/mistral_common/protocol/instruct/request.py)
```

**Expected behavior**
Same model that worked with 0.3.6 to work with 0.3.8 too.

**Additional context**

Minimal fix that worked for me is:
```
diff --git i/pyproject.toml w/pyproject.toml
index 9a57f78..d95ed03 100644
--- i/pyproject.toml
+++ w/pyproject.toml
@@ -85,6 +85,7 @@ audio = [
     # sts extra: tts deps + stt deps + webrtcvad
     "mlx-audio[tts,stt,sts] @ git+https://github.com/Blaizzy/mlx-audio@51753266e0a4f766fd5e6fbc46652224efc23981",
     "python-multipart>=0.0.5",
+    "mistral-common[audio,image]>=1.10.0",
 ]
 dev = [
     "pytest>=7.0.0",
mstenber@hana ~/git/omlx>
```

**Comment by yoyo930021** [comment]
+1, hit this on the macOS .app bundle (0.3.8) with `BRlin/Breeze-ASR-25-mlx-bf16`.

Confirmed `.app` ships `mistral_common-1.9.1.dist-info` while the brew formula ships `mistral_common-1.11.2`, so the brew install is unaffected and the .app bundle is broken for any whisper-family STT model — not specific to a model or to missing files.

Reproduces with the exact same `Could not load WhisperProcessor: cannot import name 'ReasoningEffort' from 'mistral_common.protocol.instruct.request'` warning buried in the mlx-audio post-load hook.

Looking forward to a fix.

**Comment by jundot** [comment]
Thanks for the detailed repro. Pinned mistral-common>=1.10 at top-level in #1116 and dropped the related stub in b0ffedc. Will ship in the next release.
