### PR TITLE
fix(scheduler): convert QSA singleton caches to batched form before extend

### LINKED ISSUE #3213: Cache corruption error running throughput benchmarks for Qwen3.8-Flash-Next-oQ4e-mtp
Running the throughput benchmarks for the 0.6.3 release with `Jundot/Qwen3.8-Flash-Next-oQ4e-mtp` and getting the following error:

`Cache corruption not recoverable after retries: 'QSAKVCache' object has no attribute 'extend'`

Log shows the following traceback:

```
2026-08-27 14:32:27,998 - omlx.scheduler - WARNING - [-] - Cache corruption detected: 'QSAKVCache' object has no attribute 'extend', clearing cache and re-prefilling...
2026-08-27 14:32:27,998 - omlx.scheduler - DEBUG - [-] - Cache corruption traceback:
Traceback (most recent call last):
  File "/Applications/oMLX.app/Contents/Resources/omlx/scheduler.py", line 11651, in step
    responses = list(self.batch_generator.next_generated())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_lm/generate.py", line 1866, in next_generated
    prompt_responses, generation_responses = self._next()
                                             ^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_lm_mtp/batch_generator.py", line 296, in patched_bg_next
    return original_bg_next(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_lm/generate.py", line 1819, in _next
    self._generation_batch.extend(gen_batch)
  File "/Applications/oMLX.app/Contents/Resources/omlx/patches/mlx_lm_mtp/batch_generator.py", line 237, in patched_extend
    result = original_extend(self, batch, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/Python/framework-mlx-base/lib/python3.11/site-packages/mlx_lm/generate.py", line 1296, in extend
    self.prompt_cache = _extend_cache(self.prompt_cache, batch.prompt_cache)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/scheduler.py", line 1036, in _patched_extend_cache
    return [_extend_cache_layer(ca, cb) for ca, cb in zip(cache_a, cache_b)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/scheduler.py", line 1036, in <listcomp>
    return [_extend_cache_layer(ca, cb) for ca, cb in zip(cache_a, cache_b)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/oMLX.app/Contents/Resources/omlx/scheduler.py", line 1009, in _extend_cache_layer
    cache_a.extend(cache_b)
    ^^^^^^^^^^^^^^
AttributeError: 'QSAKVCache' object has no attribute 'extend'

```

**Desktop (please complete the following information):**
 - macOS Version: 26.6.2 (25G83)
 - oMLX Version: 0.6.3

**Additional context**
I believe I've found the cause, working on a potential fix and validating locally.

### PR DESCRIPTION
**Pull request by HaloFour**
## Summary

- Let the scheduler's `_to_batched_cache_layer` fall back to a cache's own `to_batch()` conversion for model-owned singletons outside the `mlx_lm` cache hierarchy (e.g. `QSAKVCache` from the Qwen4-Exp overlay).
- Batched caches never define `to_batch`, so an already-batched layer passes through untouched and is still extended in place.

## Problem

Follow-up to #3188, which fixed the `_make_cache` seam. The singleton pass-through optimization keeps a one-row batch's cache as a singleton (`QSAKVCache` has `filter` + `extract`). When a second row later joins the batch — e.g. after an MTP late-join handoff — `GenerationBatch.extend` → `_extend_cache_layer` crashes because the singleton has no `extend` (only `BatchQSAKVCache` does):

```text
AttributeError: 'QSAKVCache' object has no attribute 'extend'
```

The scheduler's corruption handler then clears the entire cache and re-prefills, so throughput benchmarks on Qwen3.8 Flash Next (QSA) models take a large, recurring perf hit.

Fixes #3213

## Validation

- New regression tests reproduce the exact `AttributeError` at `scheduler.py:1009` without the fix and pass with it; they verify KV rows, offsets, left-padding, and QSA indexer keys/positions survive the conversion, and that the singleton pass-through and batched in-place extend behaviors are unchanged.
- Focused cache/scheduler/batching suites: `522 passed`
- Full suite excluding slow/integration: `10402 passed`; the 46 failures are byte-identical with and without the change (pre-existing dflash/web-search/float-tolerance issues).

### CODE REVIEW

**Comment by latent-variable** [comment]
Testing was confirmed on an M5 Max with 128 GB. The settings used were `Jundot/Qwen3.8-Flash-Next-oQ4e-mtp`, Lightning MTP on, and PLE SSD offload on.

Without this patch, the built-in benchmark's batch phase fails at batch 2, with exactly the error reported in #3213: `Cache corruption not recoverable after retries: 'QSAKVCache' object has no attribute 'extend'`. With the patch applied, the same run finishes:

| batch | pp tok/s | tg tok/s | avg TTFT |
|---|---|---|---|
| 2 | 565.0 | 56.1 | 2774.7 ms |
| 4 | 506.7 | 91.9 | 4710.4 ms |

In the same run, a single-request pp1024 reached 946.5 tok/s.

I ran this on top of #3225 and #3235. Those PRs affect the Qwen4 MTP capture and the PLE gather. There was no interaction between them, and the full suite is unchanged from `main`.

**Comment by jundot** [comment]
Thanks for the clear fix and the thorough cache-invariant coverage. #3246 has now landed the same scheduler conversion with adapted regression coverage. I’ll carry the two unique batch-extension edge tests into a small follow-up, so I’m closing this as superseded. I appreciate the careful reproduction and validation.
