### ISSUE TITLE
omlx 0.3.8: omlx.server - ERROR - [-] - POST /v1/chat/completions → 500 (unhandled): 'PreTrainedConfig' object has no attribute 'max_position_embeddings'

### ISSUE THREAD

**Issue by mjskraju** [jundot/omlx#1020]
**Describe the bug**

**To Reproduce**
1. Start omlx server and start loading Step-3.5-Flash-4bit model

**Expected behavior**
Successfully load the model and use it. 

**Screenshots**
<img width="1275" height="346" alt="Image" src="https://github.com/user-attachments/assets/84aaec92-25d2-4b5f-a9bc-720c3a1963bc" />

<img width="1148" height="39" alt="Image" src="https://github.com/user-attachments/assets/01eaffe5-043f-4b1e-9d29-f7c0c25d89c3" />

<img width="1063" height="44" alt="Image" src="https://github.com/user-attachments/assets/63407127-5fee-457a-98b0-93d218bb0e5a" />

<img width="795" height="121" alt="Image" src="https://github.com/user-attachments/assets/7ce5f198-e9be-48d4-af9f-a47f4ff74c3c" />

**Desktop (please complete the following information):**
 - macOS Version: Tahoe 26.4.1
 - oMLX Version: 0.3.8

**Additional context**
This model worked with omlx 0.3.6 and 0.3.7 versions. I could load and chat. But with 0.3.8 it doesn't load anymore. On the model side nothing changed, I do see max_position_embeddings in the config.json file within the model's directory.
