### ISSUE TITLE
0.6.1: engine loop crashes with 'TurboQuantMSEState' object has no attribute 'ndim' when turboquant_kv is enabled (qwen35 verify SDPA split)

### ISSUE THREAD

**Issue by alxedelweiss** [jundot/omlx#2780]
**Environment:** oMLX 0.6.1, M5 Pro 64GB, `Qwen3.8-27B-oQ8e-mtp`, `mtp_enabled: true`, `turboquant_kv_enabled: true` (`kv_bits: 4`).

**Symptom:** Every chat request stalls (client waits until its own timeout) and the engine loop dies:

```
omlx.engine_core - ERROR - Engine loop error: 'TurboQuantMSEState' object has no attribute 'ndim'
```

Worked fine on 0.6.0 with the identical config.

**Traceback (bottom frames):**

```
File ".../omlx/patches/qwen35_verify_sdpa_split.py", line 132, in patched_target_verify_attention
    limit = _eligible(queries, keys, cache)
File ".../omlx/patches/qwen35_verify_sdpa_split.py", line 78, in _eligible
    if queries.ndim != 4 or keys.ndim != 4:
File ".../mlx_vlm/turboquant.py", line 4953, in __getattr__
    return getattr(self._state, name)
AttributeError: 'TurboQuantMSEState' object has no attribute 'ndim'
```

**Root cause:** The new batched-verify eligibility gate from #2751 dereferences `keys.ndim` (line 78) *before* the quantized-cache exclusion at line 82 (`hasattr(cache, "bits")`). With TurboQuant KV, `keys` is the TurboQuant wrapper whose `__getattr__` proxies to `TurboQuantMSEState`, so the shape check itself raises — before the patch's intended stock-path fallback can engage. The engine loop dies instead of falling back.

**Local fix that restored service** (verify path falls back to stock, as #2751 intended for unsupported inputs):

```diff
-    if queries.ndim != 4 or keys.ndim != 4:
+    if getattr(queries, "ndim", 0) != 4 or getattr(keys, "ndim", 0) != 4:
         return 0
```

`getattr` with a default swallows the wrapper's AttributeError → returns 0 → ineligible → original attention path. Verified working; TurboQuant KV and MTP both stay active. A proper fix might instead reorder the checks or test `isinstance(keys, mx.array)` first — and #2751's speedup presumably still won't engage with quantized KV, which may deserve a note in the docs.

**Comment by aaramos** [comment]
Same root cause as #2778 — fix + regression test up in #2782.
