### ISSUE TITLE
Gemma-4-12b with omlx error loading model

### ISSUE THREAD

**Issue by benb0jangles** [jundot/omlx#1652]
i get error when running this model:
gemma-4-12B-it-bf16
omlx v0.3.12
error:
Error: {"error":{"message":"Internal server error","type":"server_error","param":null,"code":null}} 

other gemma-4 models (non-12b) work fine.

**Comment by warpedgeoid** [comment]
It doesn't look like the new unified model format is supported just yet.

**Comment by benb0jangles** [comment]
will the support of this model include gemma-4's audio function too #1651

**Comment by oldcai** [comment]
```
2026-06-04 17:50:18,282 - root - ERROR - [-] - Model type gemma4_unified not supported. Error: No module named 'mlx_vlm.speculative.drafters.gemma4_unified'
2026-06-04 17:50:18,289 - omlx.engine_pool - WARNING - [-] - VLM loading failed for gemma-4-12B-it-bf16, falling back to LLM: Model type gemma4_unified not supported. Error: No module named 'mlx_vlm.speculative.drafters.gemma4_unified'
2026-06-04 17:50:18,289 - omlx.engine.vlm - INFO - [-] - VLMBatchedEngine stopped
2026-06-04 17:50:18,334 - omlx.server - WARNING - [-] - POST /admin/api/models/gemma-4-12B-it-bf16/load → 500: VLM load failed: Model type gemma4_unified not supported. Error: No module named 'mlx_vlm.speculative.drafters.gemma4_unified'; LLM fallback also failed: Model type gemma4_unified not supported.
```

**Comment by Alfabeta01** [comment]
yes same issue with:

- mlx-community/gemma-4-12B-it-8bit
- mlx-community/gemma-4-12B-it-4bit

**Comment by jundot** [comment]
@benb0jangles @warpedgeoid @oldcai @Alfabeta01 I published `0.4.2.dev1` as a prerelease with the updated `mlx-vlm` pin for Gemma4 Unified (12B) support.

Release: https://github.com/jundot/omlx/releases/tag/v0.4.2.dev1

Please try one of the new DMGs and let me know if `gemma4_unified` still fails to load.

**Comment by EdHodgkinson** [comment]
That loads the gemma4_unified model for me! Trying out the assistant does not work as it is gemma4_unified_assistant model type, which I think needs adding here https://github.com/jundot/omlx/blob/58a9a696a4e292365d3ae9df7375d12e00e3e258/omlx/speculative/vlm_mtp.py#L57
```VLM MTP drafter '/mlx-community/gemma-4-12B-it-assistant-4bit' has model_type='gemma4_unified_assistant' (expected one of ('gemma4_assistant',)) — toggle will be ignored.```

**Comment by oldcai** [comment]
> [@benb0jangles](https://github.com/benb0jangles) [@warpedgeoid](https://github.com/warpedgeoid) [@oldcai](https://github.com/oldcai) [@Alfabeta01](https://github.com/Alfabeta01) I published `0.4.2.dev1` as a prerelease with the updated `mlx-vlm` pin for Gemma4 Unified (12B) support.
> 
> Release: https://github.com/jundot/omlx/releases/tag/v0.4.2.dev1
> 
> Please try one of the new DMGs and let me know if `gemma4_unified` still fails to load.

<img width="1301" height="815" alt="Image" src="https://github.com/user-attachments/assets/2d08f05c-5e99-41b2-9285-d17f50327d04" />

Thank you @jundot , it works.

**Comment by Alfabeta01** [comment]
Yes confirmed for

- mlx-community/gemma-4-12B-it-mxfp8
- mlx-community/gemma-4-12B-it-nvfp4

Not confirmed for:
- mlx-community/gemma-4-12B-it-8bit
Maybe there is an issue with the that build.

VLM MTP (Gemma 4 only) obviously can not be used... 
If I want to load Model gemma-4-12B-it-assistant-mxfp8 following message appears:
_VLM load failed: 'Gemma4AssistantDraftModel' object has no attribute 'language_model'; LLM fallback also failed: Model type gemma4_unified_assistant not supported._
Probably not in relation but maybe goot to adress

**Comment by zviratko** [comment]
On latest HEAD it loads, but produces gibberish...
Just wait :)

**Comment by benb0jangles** [comment]
Gemma-4-12b-it-bf16
with VLM MTP
Gemma-4-12b-it-assistant-bf16
working on omlx 0.4.2.dev1
total omlx + system ram use (31gb)

not a bad llm if you only have 48gb ram macbook, but (early days) i think for me gemma-4-26b-a4b-it-bf16
with
gemma-4-26b-a4b-it-assistant-bf16 (VLM MTP) (on 64gb mac max)
may be more supreme (MoE 26b vs Dense 12b). But i look forward to experimenting with 12b audio analysis

llm 'Dense-off'
Gemma-4-12b-it-bf16 (useable slow)
vs
Gemma-4-31b-it-MLX-8bit (very slow generating/response)

**Comment by Surfire** [comment]
> [@benb0jangles](https://github.com/benb0jangles) [@warpedgeoid](https://github.com/warpedgeoid) [@oldcai](https://github.com/oldcai) [@Alfabeta01](https://github.com/Alfabeta01) I published `0.4.2.dev1` as a prerelease with the updated `mlx-vlm` pin for Gemma4 Unified (12B) support.
>
> Release: https://github.com/jundot/omlx/releases/tag/v0.4.2.dev1
>
> Please try one of the new DMGs and let me know if `gemma4_unified` still fails to load.

I can load and perform text inference normally in OMLX, but it seems unable to recognize and infer images. The model says, "It can't see the images."

**Comment by benb0jangles** [comment]
> I can load and perform text inference normally in OMLX, but it seems unable to recognize and infer images. The model says, "It can't see the images."

omlx chat drops image vision capability sometimes/often in all vision models, i find being more specific with prompt - or restarting omlx - or simply repeating prompt until 'it gets it' is one solution to the problem, same issue happens in pi agent and i guess other agents too, still may be omlx not configured correctly for gemma-4-12b though idk yet. audio defo not working in omlx chat (not implemented)

**Comment by fry69** [comment]
FYI: There seems to be a fresh bug in `oMLX` chat that drops/forgets images quickly. I remember they persisted for much longer in the past.

**Comment by benb0jangles** [comment]
> [@benb0jangles](https://github.com/benb0jangles) [@warpedgeoid](https://github.com/warpedgeoid) [@oldcai](https://github.com/oldcai) [@Alfabeta01](https://github.com/Alfabeta01) I published `0.4.2.dev1` as a prerelease with the updated `mlx-vlm` pin for Gemma4 Unified (12B) support.
> 
> Release: https://github.com/jundot/omlx/releases/tag/v0.4.2.dev1
> 
> Please try one of the new DMGs and let me know if `gemma4_unified` still fails to load.

```
/opt/homebrew/opt/omlx/libexec/bin/pip install \
  "git+https://github.com/Blaizzy/mlx-vlm@041f8891176996c916f347e542b3aae179300546" \
  --force-reinstall --no-deps
```

**Comment by zviratko** [comment]
Beware that it loads, responds in chat, but if you try something more (like what benchmark does), then it produces gibberish
don't plug it into your agents yet

**Comment by jundot** [comment]
Just released v0.4.2.dev2 with Gemma4 unified MTP and VLM image recognition support.
Release notes: https://github.com/jundot/omlx/releases/tag/v0.4.2.dev2

**Comment by macdesire** [comment]
error in chat ver v0.4.2.dev2 model gemma-4-12B-4bit · temp=0, top_p=0.95, top_k=64
+0.0s
Starting
0.04s total 

Error: {"error":{"message":"Chat template error: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating","type":"invalid_request_error","param":null,"code":null}}

**Comment by benb0jangles** [comment]
gemma-4-12b-it-bf16 working better using omlx 0.4.2.dev2 - less gibberish. But image & audio analysis unable to work correctly:

pi agent:
<img width="862" height="1055" alt="Image" src="https://github.com/user-attachments/assets/2d78132a-88dc-4b26-a65b-752ec14481b0" />

<img width="859" height="556" alt="Image" src="https://github.com/user-attachments/assets/fdec1192-8de9-41fa-8a28-ad8ab7ac3726" />

directly in omlx browser chat works:

<img width="847" height="930" alt="Image" src="https://github.com/user-attachments/assets/75531c01-af8a-489d-9b29-342155f10ab7" />



`
But not possible to attach a .wav file and have gemma4 analyse audio 🥲🎶🎶🎶`

**Comment by macdesire** [comment]
its corrected for me on 0.4.4rc2 everything works !

**Comment by smallstepman** [comment]
getting the same error on 0.4.4 for model:`sweep-next-edit-v2-7B-mlx-8Bit` (trying to use it for FIM/code completion)
