### ISSUE TITLE
Support Prism ML Hadamard packs (Ternary Bonsai 2 27B, MLX 2-bit): dispatch to the pack's bundled loader + register its MODEL_CONFIG format

### ISSUE THREAD

**Issue by V1sMu21** [jundot/omlx#3727]
**Is your feature request related to a problem? Please describe.**

`prism-ml/Ternary-Bonsai-2-27B-mlx-2bit` cannot be loaded. oMLX correctly classifies it as a VLM (its `config.json` carries `vision_config`), then both the VLM path and the LLM fallback fail:

```
Model 'Ternary-Bonsai-2-27B-mlx-2bit' failed to load:
  VLM load failed: Model type prism_hadamard_qwen35 not supported.
   Error: No module named 'mlx_vlm.speculative.drafters.prism_hadamard_qwen35';
  LLM fallback also failed: Model type prism_hadamard_qwen35 not supported.
  Reload models after fixing the files to retry.
```

That `not supported` is **expected and correct**: the pack must be loaded by the loader it bundles in `runtime/`. What is missing is oMLX wiring that loader in.

**Why we cannot simply make the model type resolvable**

The pack stores its language projections in a **rotated basis**: every matrix is blockwise Hadamard-transformed (block 1024, explicit ±1 signs, declared in `hadamard.json`) before the ternary `{−1, 0, +1}` assignment, and the runtime must apply the matching transform to **activations** plus the inverse to the **embedding lookup**. Stock mlx-lm / mlx-vlm do neither, and crucially they **do not raise** — they return wrong output.

Prism ML's own demo therefore refuses to serve these packs over MLX servers (`scripts/start_mlx_server.sh` in PrismML-Eng/Bonsai-demo):

> "No MLX server for Bonsai 2 yet. Its MLX pack needs the loader bundled in the pack, which mlx_lm.server and mlx_vlm.server do not use; **serving through them would return wrong output**."

So the fix has to be "load through the bundled loader", **not** "let the model type resolve". I verified the wrong road fails loudly for the wrong reason, too: normalizing `model_type` to `qwen3_5` and feeding it to the stock path immediately trips the pack's own guard (`Unsupported packed model schema`) — and any loader that bypasses that guard silently produces garbage.

**There is a second, independent failure that survives a working loader**

Even once the model loads, `mlx_vlm.prompt_utils.MODEL_CONFIG` has no `prism_hadamard_qwen35` entry, so `get_message_json()` raises `Unsupported model`. That aborts oMLX's `_format_messages_for_vlm_template()` as a whole and falls back to the generic formatter, which emits **no image placeholders** — while oMLX still extracts the images. Every vision request then dies with:

```
ValueError: Image features and image tokens do not match: tokens: 0, features 64
```

This is the same failure mode oMLX already documents for `glm5_next` in `omlx/patches/mlx_vlm_glm5_next_compat/__init__.py`, and the same fix applies: register the type against the base model's `MessageFormat` (`qwen3_5` → `LIST_WITH_IMAGE_FIRST`).

**Describe the solution you'd like**

Follow the existing `mlx_vlm_*_compat` convention and dispatch through the extension point that `paroquant` / `qwen38_modelopt_mixed` already use, i.e. `omlx/utils/model_loading.py::maybe_load_custom_quantization()`:

1. New `omlx/patches/mlx_vlm_prism_hadamard/__init__.py`:
   - `is_supported_config(config)` — identifies the pack from metadata the pack itself declares (`model_type == prism_hadamard_qwen35`, `components.vision`), so a renamed directory or a future Bonsai size still works
   - `load(dir)` — imports `<pack>/runtime/` and calls its own `vision_artifact.load_vl_model()`
   - `apply()` — registers `prism_hadamard_qwen35` in `MODEL_CONFIG` (copying `qwen3_5`'s format)
   - **sha256-pins `runtime/*.py`** against the revision Prism ML publishes in `Bonsai-demo/scripts/bonsai2-runtime.sha256`, refusing anything that does not match. Because the loader applies weight-basis transforms, an unreviewed `runtime/` does not fail — it silently produces wrong numbers, which is worth the pin.
2. One 21-line insertion in `model_loading.py` (the diff is below).

Non-Prism models are untouched: the branch is only entered when `model_type == prism_hadamard_qwen35`.

**Two implementation details worth knowing**

- `<pack>/runtime/` has **no `__init__.py`** and its modules import each other **unqualified** (`from codec import transcode`, `from runtime import Packed`) — it is designed to be put straight on `sys.path`. A plain package import therefore raises `ModuleNotFoundError`. The loader builds a synthetic namespace package (`types.ModuleType` + `__path__`), then `import_module("<pkg>.<name>")`, plus bare-name aliases.
- Reuse the pack's own `build_processor()`. It already routes around the torch-gated `AutoProcessor`, which cannot resolve our `model_type` through transformers' `AutoConfig` (this is exactly the problem `_patch_torch_free_image_processor` handles for `glm_ocr` / `dots_ocr`).

**Describe alternatives you've considered**

- **Just map the model type to `qwen3_5`** — rejected, see above: it either fails the pack's schema guard or silently yields wrong output.
- **Vendor `runtime/` into `omlx/patches/.../vendor/`**, as `mlx_vlm_inkling_compat` does — viable, but Prism ML version-pins and revises that runtime, so vendoring would need re-syncing. I would rather reference the pack's own copy with a hash pin; happy to do it your way if you prefer vendoring.

**Additional context**

I have a working implementation and tested it locally against `main`'s `model_loading.py` (v0.7.0.dev3) — the anchor for the insertion is present and the patch applies with `patch -p0`. Verified on oMLX 0.6.4 / build 260830015308-macos26-27, macOS 26.5.1, Apple Silicon, mlx 0.32.0 / mlx-lm 0.31.3 / mlx-vlm 0.6.3:

| check | result |
|---|---|
| text: `17+26=` → `43`, `9*9=` → `81`, `6*7=` → `42` | pass |
| vision (yellow circle on blue): → `Yellow`, reasoning describes the image | pass |
| unrelated models (Llama-3.2-1B, all-MiniLM-L6-v2 embedding, Qwen3-VL-8B) | unaffected |
| 20 sequential requests | 20/20, 0 tracebacks, RSS ≈ 9 GB, no leak |
| `runtime/*.py` sha256 vs Prism ML's published pin | byte-for-byte match |

The dispatch diff (against `main`):

```diff
@@ -1328,7 +1348,28 @@ def maybe_load_custom_quantization(
         return None
+
+    from ..patches.mlx_vlm_prism_hadamard import (
+        is_supported_config as _is_prism_hadamard_pack,
+        load as _load_prism_hadamard_pack,
+    )
 
+    if is_vlm and _is_prism_hadamard_pack(config):
+        # Prism ML "Hadamard" packs (Ternary Bonsai 2) store their language
+        # projections in a rotated basis ... mlx-lm / mlx-vlm do not apply the
+        # matching activation transform, so they return *wrong output rather
+        # than an error*.  Use the pack's bundled loader instead.
+        logger.info(
+            "Prism Hadamard pack detected for %s; using its bundled loader",
+            model_name,
+        )
+        return _load_prism_hadamard_pack(model_name)
+
     quant_config = config.get("quantization_config")
```

Note oMLX already ships `omlx/custom_kernels/bonsai/` and `omlx/patches/bonsai_t5_load.py`, i.e. the Bonsai family is already known here — this is the missing member of that family. I am happy to open a PR with the patch module + a regression test if you want it; just tell me whether you prefer the bundled-loader-with-hash-pin form or a vendored copy.

**Comment by TobiasvonCarnap** [comment]
Same failure here on oMLX 0.6.4 / M3 Max 64 GB, macOS 26.5.1 — Model type prism_hadamard_qwen35 not supported, both paths. Pack downloaded and settings in place, happy to verify your patch on a second machine if you open the PR. I can also run the text/vision checks plus a longer sequential run.

**Comment by quim3ra** [comment]
Would it be nice, if you fork it and create the pr.

Thanks!

**Comment by johnlovesgoats** [comment]
+1

**Comment by quim3ra** [comment]
Here you have an open branch that works:

https://github.com/quim3ra/omlx/tree/fix/hadamard_quant

Thanks to @V1sMu21 for pointing me to the right direction to at least having it ready

**Comment by V1sMu21** [comment]
Status update for anyone watching this issue.

The fix is **PR #3734** ("fix: support Prism Hadamard Qwen3.5 model packs", by @samfenwick), which references `Fixes #3727`. CI is green on 3.11/3.12/3.13 and it is mergeable. Two things worth knowing if you are following along.

**1. It addresses both root causes reported here**

- The rotated-basis loader is vendored into `omlx/patches/prism_hadamard/`: the Hadamard activation transform and the inverse embedding transform are applied by oMLX itself, and it deliberately does **not** execute Python from the downloaded checkpoint's `runtime/`. That is a better shape than the bundled-loader-with-hash-pin approach I originally proposed.
- `MODEL_CONFIG` gains the `prism_hadamard_qwen35` entry, which is the fix for the second, independent failure in the report — the silent image-token dropout (`Image features and image tokens do not match: tokens: 0, features N`).

I checked the PR's loader against the published pack (0.6.4, MLX 0.32.0): its `_validate_config` gate accepts it unchanged — `schema_version=2`, `quantization={bits:2, group_size:128, mode:affine}`, `gdn_activation_layout=grouped`, 402 module records — so the gate is not stricter than what prism-ml actually ships. The model builds and `MODEL_CONFIG` registers.

**2. On oMLX 0.6.4, this needs a release carrying a newer mlx-vlm first**

@TobiasvonCarnap — flagging this before you spend time on a verification run, since you are on 0.6.4 too. On this machine (0.6.4, mlx-vlm 0.6.3) the PR's loader loads the pack fine, but the first decode step raises:

```
TypeError: CapacityPreservingModel.__call__() got an unexpected keyword argument 'gdn_sink'
```

The PR installs its subclass as `language_model.model.__class__`, and 0.6.3's `qwen3_5/language.py` forwards a `gdn_sink` kwarg into that object. `main` pins mlx-vlm at `3fb24e90`, whose copy of that file contains no `gdn_sink` at all — so this is release/pinned-commit skew, not a defect in the PR. I have written the reproduction and the grep-level discriminator up in a comment on #3734 rather than here.

So the practical sequence is: wait for the PR to land *and* for a release built against the newer mlx-vlm. Patching it into an existing 0.6.4 install is not expected to work on its own.

**One housekeeping note**

@quim3ra's branch `fix/hadamard_quant` was the earlier working reference — it loads through the pack's own `runtime/vision_artifact.py`. #3734 supersedes it (not executing checkpoint code, plus the added weight validation and long-context handling), so there is no need to carry both.
