### ISSUE TITLE
SpecPrefill × TurboQuant KV: the BatchTurboQuantKVCache half of #766 still deadlocks on 0.5.3 (SpecPrefill cache never quantised + non-recovering cache-error path)

### ISSUE THREAD

**Issue by necoli1822** [jundot/omlx#2336]
## Summary

> **Note:** This report was not written directly by a human. The investigation and root-cause analysis were carried out together with **Claude Opus (Anthropic)**, and the write-up was drafted by the model. I have reviewed the findings and reproduced/verified them on my own machine before filing. Apologies in advance for anything that reads as machine-generated — I'm happy to clarify or provide more detail on request.

This is a follow-up to **#766** ("SpecPrefill AttributeError **and** BatchTurboQuantKVCache Corruption").

**#2273 fixed the RoPE half and I can confirm it works on 0.5.3** — the `'_OffsetAdjustedRoPE' object has no attribute 'dims'` error is gone, and `_OffsetAdjustedRoPE` re-wrapping / `_unwrap_rope()` behave as intended.

But #2273 explicitly noted *"this PR does not touch the BatchTurboQuantKVCache part of that issue"*, and **that half is still broken on 0.5.3** — and now it's worse: instead of a logged error with dense fallback, it causes a **hard hang** (no tokens, no error to the client, until the client aborts minutes later).

I traced it to two distinct bugs:

- **Bug A (trigger):** SpecPrefill's sparse-prefilled cache is **never TurboQuant-converted**, so it enters the batch as a plain `BatchKVCache` while normally-prefilled requests are `BatchTurboQuantKVCache`. Merging them raises `BatchTurboQuantKVCache.extend expected BatchTurboQuantKVCache, got BatchKVCache` — this is the 0.5.3 form of #766's old `'BatchTurboQuantKVCache' object has no attribute '_idx'` symptom (the batch-cache alignment work added an explicit type check that now surfaces the same underlying mismatch cleanly).
- **Bug B (the hang):** `_recover_from_cache_error()` does not clear the active SpecPrefill state, so the "recovery" deadlocks the scheduler instead of recovering.

Fix A stops the corruption; Fix B makes the (designed) recovery actually recover. Both patches + a controlled repro below.

## Environment

- **omlx 0.5.3**
- macOS 26.5.1 (25F80), Apple M5, 32 GB
- Model: `Qwen3.6-35B-A3B` (Qwen3.5 tokenizer family — **not** Gemma/MXFP4), hybrid linear/full-attention MoE
- Settings: `turboquant_kv_enabled: true`, `turboquant_kv_bits: 4`, `turboquant_skip_last: true`, `specprefill_enabled: true`, `specprefill_keep_pct: 0.25`

## Symptom

With both TurboQuant KV and SpecPrefill on, a request large enough to take the sparse-prefill path (~15–20k-token multi-turn context) while a normal TurboQuant request is already in the batch produces **zero output** and the logs go silent until the client aborts (`stream_generate Aborting request … finished_normally=False`). Short/single-shot requests never take the sparse path, so they work — which makes it look intermittent.

### Bug A — SpecPrefill caches skip TurboQuant conversion

`omlx/specprefill/target.py` builds its cache with the stock factory (`make_prompt_cache(target_model)`) and returns it unchanged — plain `KVCache` layers, never quantised.

In `omlx/scheduler.py` (`_schedule_waiting`), the SpecPrefill branch (`if request.specprefill_indices is not None:`) sets `cache_to_use = target_result.prompt_cache` and then falls through. But the **only** code that runs `_apply_turboquant_kv_convert()` lives in the `if request.specprefill_indices is None:` block that follows (via `_do_external_prefill()` and `_insert_prefilled_request()` → `_finalize_chunked_prefill_cache_for_insert()`). SpecPrefill requests skip that block entirely, so their cache is never converted.

The stale assumption is even documented in-line right before insert:

```python
# TurboQuant KV is quantized at the end of _do_external_prefill
# (fp16 prefill → quantize once); _merge_caches() turns the per
# request TQ cache into a BatchTurboQuantKVCache on insert.
```

…but `_do_external_prefill()` is exactly the call SpecPrefill skips. The plain cache is inserted as `BatchKVCache`; when later merged with a TurboQuant batch cache, `_extend_cache_layer()` → `BatchTurboQuantKVCache.extend(other)` in `omlx/turboquant_kv.py` raises `expected BatchTurboQuantKVCache, got BatchKVCache`.

### Bug B — cache-error recovery leaves SpecPrefill state dangling → deadlock

`_reschedule_running_requests(is_corruption=True, max_corruption_retries=3)` is meant to make this recoverable. But `_recover_from_cache_error()` resets `batch_generator`, caches, UID maps, VLM state, detokenizers — and **not** `_specprefill_active_request_id` (and never calls `cleanup_rope`). That id is only cleared in `_cleanup_specprefill()` and one `_requeue_or_fail_prefill()` path, neither of which runs here.

The scheduler gate then deadlocks every subsequent step:

```python
# _schedule_waiting
if self._specprefill_active_request_id is not None:
    # a specprefill request is decoding with its offset RoPE installed;
    # defer everything, including other specprefill requests
    self.waiting.appendleft(request)
    break
```

So: corruption fires while SpecPrefill is active → recovery leaves the id set → next step defers **all** requests and `break`s → the rescheduled re-prefill never runs → the id is never cleared → **permanent hang** (no output, and it never even reaches the 3-retry failure path).

The sibling handler `_recover_from_generation_overflow_error()` already handles this correctly:

```python
active_specprefill = self._specprefill_active_request_id
if active_specprefill is not None:
    self._cleanup_specprefill(active_specprefill)
```

`_recover_from_cache_error()` is just missing the same lines.

## Reproduction & verification (controlled, same host + model)

**Stock 0.5.3 — hang reproduces deterministically.** A ~20k-token multi-turn request while a normal request is in the batch:

```
TurboQuant: converted 9/40 cache layers to 4.0-bit, skipped last KVCache layer   # prior request builds the TQ batch
SpecPrefill: scored 13806 tokens ... (keep=25%, prompt 20082 = system 6276 + conv 13806)
SpecPrefill: system prompt 6276 tokens full prefill
SpecPrefill: sparse prefill 3456/13806 conv tokens in 13.6s
Cache corruption detected: BatchTurboQuantKVCache.extend expected BatchTurboQuantKVCache, got BatchKVCache, clearing cache and re-prefilling...
# --- then silence; the request never completes; client aborts minutes later ---
```

**With both fixes applied — same workload completes, no corruption:**

```
SpecPrefill: sparse prefill 3456/13806 conv tokens in ...
TurboQuant: converted 9/40 cache layers to 4.0-bit, skipped last KVCache layer   # <-- the SpecPrefill cache is now converted too
Chat completion: NN tokens in ...s
```

The tell is the `TurboQuant: converted …` line that now appears **immediately after** `SpecPrefill: sparse prefill …` — proof the SpecPrefill cache is finally quantised so its layers match the batch.

I verified both directions: applied the patches → real workload (an opencode coding agent, ~20k-token sessions) runs cleanly with zero `Cache corruption detected`; reverted to stock 0.5.3 → the hang reproduces on the identical workload every time; re-applied → clean again.

### Fix A — convert the SpecPrefill cache before insert (`omlx/scheduler.py`, SpecPrefill success branch)

```diff
                     cache_to_use = target_result.prompt_cache
                     tokens_to_process = target_result.tokens_to_process
                     self._specprefill_active_request_id = request.request_id
 
+                    # SpecPrefill bypasses the external-prefill block below
+                    # (specprefill_indices is not None), which is the only path
+                    # that runs _apply_turboquant_kv_convert. The sparse cache
+                    # from run_specprefill_target_prefill() is therefore still a
+                    # plain fp16 KVCache. Convert it here so it matches the
+                    # TurboQuant batch caches; otherwise BatchTurboQuantKVCache
+                    # .extend rejects it as a plain BatchKVCache on batch merge.
+                    if self._turboquant_kv_bits is not None and \
+                            self._turboquant_eligible(cache_to_use):
+                        self._apply_turboquant_kv_convert(cache_to_use)
 
                     # Mark spec-prefill complete (auto-removes tracker entry).
                     tracker.update(request.request_id, total_pp, total_pp, model_id)
```

This mirrors `_finalize_chunked_prefill_cache_for_insert()`; as a bonus it restores TurboQuant KV memory savings for SpecPrefill requests, which were silently running fp16 KV.

### Fix B — clear SpecPrefill state in cache-error recovery (`omlx/scheduler.py`, `_recover_from_cache_error`)

```diff
         self._boundary_snapshot_required = None
 
+        # A corruption that fires while a SpecPrefill request is active leaves
+        # _specprefill_active_request_id set and an offset RoPE installed on the
+        # shared model. Without clearing it, _schedule_waiting defers every
+        # request at the specprefill gate and the re-prefill deadlocks (no
+        # output until the client aborts). Mirror
+        # _recover_from_generation_overflow_error.
+        active_specprefill = self._specprefill_active_request_id
+        if active_specprefill is not None:
+            self._cleanup_specprefill(active_specprefill)
 
         # Clear stale VLM position state to prevent re-corruption on retry
         if hasattr(self.model, "clear_vlm_position_state"):
```

## Notes

- Fix A alone removes the symptom; Fix B is defence-in-depth so any future mid-SpecPrefill corruption recovers instead of deadlocking. Both seem worth landing.
- Possibly related, not fixed here: the SpecPrefill "must be alone in the batch" guard checks only `len(scheduled) > 0` (this round's newly scheduled requests), not `self.running`, so a SpecPrefill request can still join a batch that already has a running request — which is the concurrency window that lets Bug A's mismatch happen at all. Tightening that guard may be a more fundamental fix, but the two patches above are sufficient to eliminate the hang.

Happy to open this as a PR with tests (same style as #2273) if you'd prefer.
